### ISSUE TITLE
Double Check prior biased distribution adjustment for testing and validation predictions

### ISSUE THREAD

**Issue by tmachnitzki** [m-dml/plankton-classifier#38]
https://github.com/m-dml/plankton-classifier/blob/4ac85cdbca99e68195d03136cede9579e90b6abf/src/models/LightningBaseModel.py#L387-L396

As mentioned by @dgreenberg I included a correction for the posterior probabilities by using the information about the label distribution from the training dataset before it gets balanced.

**Comment by dgreenberg** [comment]
maybe give `outputs` a more descriptive name and/or docstring. should be apparent that its probs and not log probs without looking into code

**Comment by dgreenberg** [comment]
need to multiply by p_corrected_per_class, not divide

**Comment by dgreenberg** [comment]
after the multiplication, all we need is a (log) soft max, no need to calculate the denominator explicitly
